version: "3.8"

services:
  frontend:
    image: 490004653796.dkr.ecr.us-east-2.amazonaws.com/tiger-traits-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    networks:
      app_network:
        aliases:
          - frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/ # internal networking
      #- REACT_APP_API_URL=http://tigertraits-app-env.eba-2mmpc3td.us-east-2.elasticbeanstalk.com/api  # Use backend's container name

  backend:
    image: 490004653796.dkr.ecr.us-east-2.amazonaws.com/tiger-traits-backend:latest
    container_name: backend # set explicitly
    restart: always
    ports:
      - "5000:5000"
    networks:
      app_network:
        aliases:
          - backend # alias for internal networking
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/mydatabase?authSource=admin
      #internal networking
      #- MONGO_URI=mongodb://mongo:27017/mydatabase  # Connect to the MongoDB container
      #- PORT=5000

  mongo:
    build: ./mongo # Build Mongo from the Dockerfile in the "mongo" directory
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      app_network:
        aliases:
          - mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=mydatabase

networks:
  app_network:
    driver: bridge